name: Create Fmod native build
description: Creates fmod native build for a specific platform
runs:
  using: composite
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Download fmod jar
      uses: actions/download-artifact@v4
      with:
        name: fmod-jar
        path: android-plugin/library/libraries/

    - name: Build android plugin
      uses: eskatos/gradle-command-action@v1
      with:
        wrapper-directory: android-plugin/
        build-root-directory: android-plugin/
        arguments: :library:build